Style/AccessModifierIndentation:
  EnforcedStyle: outdent
  SupportedStyles:
    - outdent
    - indent
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Rails:
  Enabled: true
Style/StringLiterals:
  Enabled: false
